### ISSUE TITLE
add a networkId input box so much better

### ISSUE THREAD

**Issue by WaterSunMount** [hassio-addons/addon-zerotier#161]
# Problem/Motivation

> (Why the issue was filed)
When I first installed, I clicked on the `Configuration`  page and there was only one `api_auth_token`  input box. I thought it was to input the networkId, but there was no response after input,Until I looked at the documentation and found that there was a configuration for the networkId, but it needed to be edited with yaml

## Expected behavior

> (What you expected to happen)
I would like to have two input boxes, one for `api_auth_token` and one for `networkId`

## Actual behavior

> (What actually happened)
one input box is confusing , because the network id is necessary

## Steps to reproduce

> (How can someone else make/see it happen)
click `Configuration` tab
## Proposed changes
I would like to have two input boxes, one for `api_auth_token` and one for `networkId`
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Agree,  the add-on is configured as such, however, the UI Home Assistant generates/provides is not always that intuitive. From an add-on perspective, there is not much I can do. Especially since network is a list (not single text field) as the add-on can join multiple networks.

Feel free to contribute/suggest an improvement @ the Home Assistant project.

../Frenck
