### ISSUE TITLE
Unable to start add on

### ISSUE THREAD

**Issue by GeradB** [hassio-addons/addon-zerotier#3]
# Problem/Motivation
Add on does not start

Log error 

19-04-03 02:30:05 ERROR (SyncWorker_0) [hassio.docker] Can't start addon_a0d7b954_zerotier: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/net/tun": no such file or directory")

**Comment by nnmalex** [comment]
I'm having the same issue. The container won't start from the UI and no container logs are available. If starting from terminal the error message says:
`
Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/net/tun": no such file or directory
`

I'm running hass OS in ESXi virtual machine.

**Comment by Kitser** [comment]
I've got the same problem. I'm running Hassio on Proxmox. 
I can't start the addon and don't get any logs in the addon.

**Comment by frenck** [comment]
# :warning: This is currently a known issue.

So please, just add a 👍 to the start topic, instead of replying with "Same for me...". Thanks :)

This issue occurs on systems running HassOS using OVA/VMDK/VM/Proxmox/ESX/.../... 
It seems like HassOS for those systems is missing the tun support in the kernel. I'm currently looking into this. Unfortunately, this is not something I can fix from the add-on, this requires an HassOS fix/update/release.

**Comment by janwilnl** [comment]
More info, it occors on my proxmox config with hassio but also with debian with hassio installed on it. I guess it works without proxmox

**Comment by frenck** [comment]
@janwilnl In case you run it on your "general linux" setup, it depends on your system... so your system is missing the tun modules, which you are responsible for to add/manage and is totally out of scope and reach for Hass.io in that case.

**Comment by frenck** [comment]
This issue has been fixed in HassOS 2.12.
Upgrade your system.
